Update PHPMailerAutoload.php
I have got an error:
Fatal error: __autoload() is no longer supported, use spl_autoload_register() instead in D:\xampp\htdocs\test\PHPMailer\PHPMailerAutoload.php on line 45

Then I edit line no 45:
function spl_autoload_register($classname)

Now my error is fixed. 
This reason for this error is
1. SPL autoloading was introduced in PHP 5.1.2
2.  __autoload() is no longer supported
So just change the function name